name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy prefect pyodbc

    - name: Set up Prefect environment variables
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: echo "Prefect environment variables set."

    - name: Build Prefect deployment
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      id: build-deployment
      run: |
        BUILD_OUTPUT=$(prefect deployment build copyfilefromlocaltosql:file_movement_flow -n "Load Data to SQL Deployment" | tail -n 1)
        echo "::set-output name=deployment_file::$BUILD_OUTPUT"

    - name: Apply Prefect deployment
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: |
        prefect deployment apply ${{ steps.build-deployment.outputs.deployment_file }}

    - name: Run Prefect deployment
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: |
        prefect deployment run "Load Data to SQL/Load Data to SQL Deployment"

    - name: Start Prefect agent
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: |
        nohup prefect agent start --pool "default-agent-pool" &
