name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy prefect pyodbc

    - name: Set up Prefect environment variables
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: echo "Prefect environment variables set."

    - name: Build Prefect deployment
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      id: build-deployment
      run: |
        prefect deployment build copyfilefromlocaltosql.py:file_movement_flow -n "Load Data to SQL Deployment"

    - name: Apply Prefect deployment
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: |
        prefect deployment apply ./*.yaml

    # - name: Execute Deployment
    #     env:
    #       PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
    #       PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
    #     run: prefect execute deployment --name my-first-deployment

    - name: Run Prefect deployment
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: |
        # prefect execute deployment --name "Load Data to SQL Deployment"
        prefect deployment run "Load Data to SQL/Load Data to SQL Deployment" --param file_path=MYFILE.csv

    - name: Start Prefect agent
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: | 
        nohup prefect agent start --pool "default-agent-pool" &
