name: Deploy Prefect flow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Replace 'x' with your desired Python version

      - name: Install Prefect
        run: pip install -U prefect

      - name: Build Deployment
        run: prefect deployment build -n my-first-deployment flow.py:hello

      - name: Apply Deployment
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: prefect deployment apply ./*.yaml

      - name: Execute Deployment
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: prefect deployment run hello/my-first-deployment

      - name: Start Prefect Agent
        run: |
          # Start the agent in the background
          prefect agent start --pool "default-agent-pool" --work-queue "default" &
          
          # Wait for the agent to pick up and complete the job
          sleep 60
          
          # Check agent logs (optional)
          tail -n 50 nohup.out

      - name: Stop Prefect Agent
        run: |
          # Find the process ID of the Prefect agent and stop it
          AGENT_PID=$(pgrep -f 'prefect agent start')
          echo "Stopping agent with PID: $AGENT_PID"
          kill $AGENT_PID
