name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy prefect pyodbc

    - name: Set up Prefect environment variables
      env:
        PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: echo "Prefect environment variables set."

    - name: Deploy Prefect flow
      run: |
        prefect deploy flow --file copyfilefromlocaltosql.py --name "Load Data to SQL Deployment"

    - name: Run Prefect flow
      run: |
        prefect run flow "Load Data to SQL Deployment"

    - name: Start Prefect agent
      run: |
        nohup prefect agent start --pool "default-agent-pool" &
