name: Deploy Prefect flow

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Prefect
        run: pip install -U prefect

      - name: Build Deployment
        run: prefect deployment build -n my-first-deployment -f deployment.yaml flow.py:hello

      - name: Apply Deployment
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: prefect deployment apply deployment.yaml
